import './style.css'
import { GoogleGenerativeAI } from '@google/generative-ai'

// --- Chatbot Logic ---

const API_KEY = import.meta.env.VITE_GEMINI_API_KEY
const MODEL_NAME = import.meta.env.VITE_GEMINI_MODEL || 'gemini-2.0-flash'

let genAI = null
let model = null
if (API_KEY && API_KEY !== 'your_api_key_here') {
  genAI = new GoogleGenerativeAI(API_KEY)
  model = genAI.getGenerativeModel({ model: MODEL_NAME })
}

const chatModal = document.getElementById('chat-modal')
const chatMessages = document.getElementById('chat-messages')
const chatInput = document.getElementById('chat-input')
const chatSend = document.getElementById('chat-send')
const closeChat = document.getElementById('close-chat')

let chatSession = null;
let currentGoal = '';
let isGeneratingReport = false;

function addMessage(text, isBot = true, isHTML = false) {
  const msgDiv = document.createElement('div')
  msgDiv.className = `msg ${isBot ? 'msg-bot' : 'msg-user'}`

  if (isHTML) {
    msgDiv.innerHTML = text
  } else {
    // Add simple formatting for bold text generated by Gemini
    let formattedText = text.replace(/\*\*(.*?)\*\*/g, '<strong>$1</strong>');
    formattedText = formattedText.replace(/\n\*/g, '<br>•');
    formattedText = formattedText.replace(/\n-/g, '<br>•');
    msgDiv.innerHTML = formattedText
  }

  chatMessages.appendChild(msgDiv)
  chatMessages.scrollTop = chatMessages.scrollHeight
}

async function openChat(goalTitle) {
  chatModal.style.display = 'flex'
  chatMessages.innerHTML = ''
  currentGoal = goalTitle
  isGeneratingReport = false

  if (!model) {
    addMessage('Lo siento, la inteligencia artificial no está encendida (falta API Key). Por favor, contacta a un especialista en el botón de abajo.', true)
    // Add fallback CTA
    const ctaDiv = document.createElement('div')
    ctaDiv.style.marginTop = '1rem'
    ctaDiv.innerHTML = `<a href="https://wa.me/573000000000?text=Hola!%20Quiero%20empezar%20mi%20plan%20de%20${encodeURIComponent(goalTitle)}." target="_blank" class="btn btn-primary" style="width: 100%; text-align: center;">Hablar por WhatsApp</a>`
    chatMessages.appendChild(ctaDiv)
    return
  }

  const systemInstruction = `
    Eres un Asesor de Bienestar de Élite de FuXion y Advanced Health.
    Tu objetivo es evaluar la salud del usuario de forma conversacional, amigable, empática y MUY humana.
    
    El usuario ha indicado que le interesa: "${goalTitle}".
    
    INSTRUCCIONES CLAVES:
    1. Saluda y menciona su interés en "${goalTitle}". Di que le harás unas preguntas rápidas para conocerlo.
    2. Haz SIEMPRE SOLO UNA PREGUNTA (o dos muy cortas y relacionadas) a la vez. ¡No lo abrumes! Muestra empatía a sus respuestas.
    3. A través de la conversación, debes indagar subrepticiamente sobre estos pilares (puedes unirlos si fluye natural):
       - Edad/Peso aproximado.
       - Descanso (Horas y calidad de sueño).
       - Alimentación e Hidratación (Procesados, agua).
       - Nivel de sedentarismo.
       - Estrés.
       - Obstáculos principales o consumo de sustancias (alcohol, tabaco).
    4. CUANDO CONSIDERES QUE TIENES SUFICIENTIENTE INFORMACIÓN (no tiene que ser perfecta, solo suficiente para hacer una recomendación coherente), debes decirle de forma natural que vas a analizar sus datos para crear su reporte.
    5. AL FINAL DE ESE ÚLTIMO MENSAJE, debes escribir EXACTAMENTE la palabra clave: [REPORT_READY].
  `;

  chatSession = model.startChat({
    history: [
      {
        role: "user",
        parts: [{ text: systemInstruction }]
      },
      {
        role: "model",
        parts: [{ text: "Entendido. Iniciaré la conversación fluyendo naturalmente y adaptándome a lo que diga el usuario. Recopilaré la info clave y terminaré con [REPORT_READY] cuando esté listo." }]
      }
    ]
  });

  // Kick off conversation
  try {
    const result = await chatSession.sendMessage(`Hola, quiero iniciar mi evaluación enfocado en: ${goalTitle}`);
    const text = result.response.text();
    addMessage(text.replace('[REPORT_READY]', ''), true);
  } catch (error) {
    console.error("Gemini Error:", error);
    addMessage('Hubo un error de conexión inicial.', true);
  }
}

async function handleUserInput() {
  if (isGeneratingReport || !chatSession) return;

  const input = chatInput.value.trim();
  if (!input) return;

  chatInput.value = '';
  addMessage(input, false);

  try {
    const result = await chatSession.sendMessage(input);
    const text = result.response.text();

    if (text.includes('[REPORT_READY]')) {
      isGeneratingReport = true;
      const cleanText = text.replace('[REPORT_READY]', '').trim();
      if (cleanText) {
        addMessage(cleanText, true);
      }
      generateReport();
    } else {
      addMessage(text, true);
    }
  } catch (error) {
    console.error("Gemini Response Error:", error);
    addMessage('Hubo un problema de conexión. Por favor, intenta de nuevo.', true);
  }
}

async function generateReport() {
  addMessage('🧬 Analizando tus biomarcadores y elaborando tu reporte premium...', true)

  try {
    const jsonPrompt = `
      Ahora, basado en TODA la información recopilada en nuestra conversación, genera el REPORTE DE BIENESTAR PREMIUM para el usuario.
      IMPORTANTE: DEBES RESPONDER ÚNICAMENTE CON UN JSON VÁLIDO. No uses formato markdown alrededor del JSON, solo el objeto JSON puro y estricto empezando con { y terminando con }. No incluyas ningún texto introductorio ni final.
      
      ESTRUCTURA EXACTA DEL JSON:
      {
        "biologicalAge": {
          "age": "X años",
          "explanation": "Breve explicación..."
        },
        "metabolicAnalysis": "Resumen de 2 oraciones sobre cómo sus hábitos impactan su meta.",
        "routine": {
          "morning": ["Acción 1", "Acción 2"],
          "afternoon": ["Acción 1", "Acción 2"],
          "night": ["Acción 1", "Acción 2"]
        },
        "products": [
          {
            "name": "Nombre Producto FuXion 1",
            "benefit": "Explicación de por qué lo necesita..."
          },
          {
            "name": "Nombre Producto FuXion 2",
            "benefit": "Explicación de por qué lo necesita..."
          }
        ]
      }
    `;

    const result = await chatSession.sendMessage(jsonPrompt);
    const response = await result.response;
    let text = response.text();

    // Clean potential markdown blocks
    let cleanText = text.replace(/```json/gi, '').replace(/```/g, '').trim();
    // Safety net for substring extraction
    const firstBrace = cleanText.indexOf('{');
    const lastBrace = cleanText.lastIndexOf('}');
    if (firstBrace !== -1 && lastBrace !== -1) {
      cleanText = cleanText.substring(firstBrace, lastBrace + 1);
    }

    const data = JSON.parse(cleanText);

    // Create a beautifully structured UI template for the report
    const reportHTML = `
      <div class="premium-report">
        <div class="pr-header">
          <h3>Tu Plan Bio-Optimizado</h3>
          <div class="pr-age-badge">Edad Biológica Estimada: <strong>${data.biologicalAge.age}</strong></div>
          <p class="pr-subtitle">${data.biologicalAge.explanation}</p>
        </div>
        
        <div class="pr-section">
          <h4><svg viewBox="0 0 24 24" width="18" height="18" fill="none" stroke="currentColor" stroke-width="2" style="vertical-align: middle;"><path d="M12 22s8-4 8-10V5l-8-3-8 3v7c0 6 8 10 8 10z"></path></svg> Análisis Metabólico</h4>
          <p>${data.metabolicAnalysis}</p>
        </div>

        <div class="pr-section">
          <h4><svg viewBox="0 0 24 24" width="18" height="18" fill="none" stroke="currentColor" stroke-width="2" style="vertical-align: middle;"><circle cx="12" cy="12" r="10"></circle><polyline points="12 6 12 12 16 14"></polyline></svg> Rutina Ideal</h4>
          <ul class="pr-routine">
            <li><span class="pr-time">🌤️ Mañana:</span> <span class="pr-action">${data.routine.morning.join(' • ')}</span></li>
            <li><span class="pr-time">☀️ Tarde:</span> <span class="pr-action">${data.routine.afternoon.join(' • ')}</span></li>
            <li><span class="pr-time">🌙 Noche:</span> <span class="pr-action">${data.routine.night.join(' • ')}</span></li>
          </ul>
        </div>

        <div class="pr-section">
          <h4><svg viewBox="0 0 24 24" width="18" height="18" fill="none" stroke="currentColor" stroke-width="2" style="vertical-align: middle;"><path d="M12 2.69l5.66 5.66a8 8 0 1 1-11.31 0z"></path></svg> Prescripción FuXion</h4>
          <div class="pr-products">
            ${data.products.map(p => `
              <div class="pr-product">
                <div class="pr-product-name">${p.name}</div>
                <div class="pr-product-desc">${p.benefit}</div>
              </div>
            `).join('')}
          </div>
        </div>
      </div>
    `

    addMessage(reportHTML, true, true)

    // Add final CTAs
    const ctaDiv = document.createElement('div')
    ctaDiv.style.marginTop = '1rem'
    ctaDiv.style.display = 'flex'
    ctaDiv.style.flexDirection = 'column'
    ctaDiv.style.gap = '0.5rem'
    ctaDiv.innerHTML = `
      <a href="https://wa.me/573000000000?text=Hola!%20Acabo%20de%20hacer%20mi%20evaluación%20celular%20de%20${currentGoal}%20y%20quiero%20empezar%20mi%20plan." target="_blank" class="btn btn-primary" style="width: 100%; text-align: center;">Hablar con Especialista (WhatsApp)</a>
      <button onclick="location.reload()" class="btn" style="background: #eee; width: 100%;">Volver a Evaluarme</button>
    `
    chatMessages.appendChild(ctaDiv)
    chatMessages.scrollTop = chatMessages.scrollHeight

  } catch (error) {
    console.error('Error Parsing Initial JSON:', error)
    addMessage('<div style="color: #e74c3c; background: #fdf3f2; padding: 1rem; border-radius: 8px;"><strong>Error de procesamiento</strong> <br><br>Pude recopilar tus datos, pero la Inteligencia Artificial tuvo un problema al estructurar el reporte premium. Por favor, intenta enviar tu evaluación por WhatsApp para revisarlo manualmente.</div>', true, true)
  }
}

// --- Event Listeners ---

document.querySelectorAll('.goal-card').forEach(card => {
  card.addEventListener('click', (e) => {
    e.preventDefault()
    const goalTitle = card.querySelector('.goal-title').textContent
    openChat(goalTitle)
  })
})

document.querySelectorAll('.start-eval-btn').forEach(btn => {
  btn.addEventListener('click', (e) => {
    e.preventDefault()
    openChat('Bienestar General')
  })
})

chatSend.addEventListener('click', handleUserInput)
chatInput.addEventListener('keypress', (e) => {
  if (e.key === 'Enter') handleUserInput()
})

closeChat.addEventListener('click', () => {
  chatModal.style.display = 'none'
  // Optionally, you could reset everything here, but left as is to allow minimizing/maximizing
})

chatModal.addEventListener('click', (e) => {
  if (e.target === chatModal) chatModal.style.display = 'none'
})
